Create qlik.md
IT-za-Edu/IT-community pull request #4
Opened 2021-03-26 14:23 UTC by galushkinrussia

2021-03-26 15:04 UTC, anst-foto commented
Подскажите к какой сфере/экспертизе/направлению больше подходит? Отдельное направление Qlik?

2021-03-26 15:29 UTC, galushkinrussia commented
BI
--
Отправлено из Mail.ru для Android пятница, 26 марта 2021г., 18:04 +03:00 от Starinin Andrey  ***@***.*** :

>Подскажите к какой сфере/экспертизе/направлению больше подходит? Отдельное направление Qlik?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-03-26 16:00 UTC, anst-foto commented
> BI -- Отправлено из Mail.ru для Android пятница, 26 марта 2021г., 18:04 +03:00 от Starinin Andrey ***@***.*** :
> […](#)
> Подскажите к какой сфере/экспертизе/направлению больше подходит? Отдельное направление Qlik? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .

Тогда нужно поместить в BI.md Если такого нет - то создать

2021-03-26 16:15 UTC, anst-foto requested changes
Необходимо добавить в файл с именем экспертизы/направления

2021-03-27 12:59 UTC, anst-foto approved these changes
Спасибо!

2021-03-27 13:00 UTC, merged